name: smart_refresh_indicator
description: "A customizable Flutter refresh indicator widget with support for background and indicator colors."
version: 0.0.2
homepage: https://github.com/fazil-kp/smart_refresh_indicator.git

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
